org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Mapbox public token (runtime map rendering)
MAPBOX_DOWNLOADS_TOKEN=pk.eyJ1Ijoiam9lLWFsYW4iLCJhIjoiY21nbTQ4NXdjMTU5NzJpb2t5MTd2eWM4eSJ9.Hx95EL3r7f9xqfEiX2yYeQ

# Mapbox secret token — required by mapbox_maps_flutter to authenticate against Mapbox Maven registry at build time (DOWNLOADS:READ scope)
SDK_REGISTRY_TOKEN=sk.eyJ1Ijoiam9lLWFsYW4iLCJhIjoiY21tN3JuZXRiMHQ5OTMxcDkwZzlzYWRlNSJ9.QArzyw5-42tnA8yzDAQFYg
